{{- if .Values.cache.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.cache.name }}
  labels:
    app: {{ .Values.cache.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: 1
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}"
        app: {{ .Values.cache.name }}

  strategy:
    type: RollingUpdate
    spec:
      containers:
      - name: redis-cache
        image: redis:latest
        imagePullPolicy: Always
        args:
        - redis-server
        - --save
        - ""
        - --maxmemory
        - {{ .Values.cache.memory }}
        - --maxmemory-policy
        - allkeys-lru
        ports:
        - containerPort: {{ .Values.cache.name }}
          name: {{ .Values.cache.name }}-tcp-port
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 6379
          timeoutSeconds: 2
{{- end }}
