name: ""
image: ""

db:
  enabled: true
  type: "postgres"
  host: "db"
  name: "app"
  username: "postgres"
  password: "password"

web:
  name: "web"
  enabled: true
  host: ""
  entrypoint: ""
  command: ""

worker:
  name: "worker"
  enabled: true
  entrypoint: ""
  command: ""

redis:
  name: "redis"
  enabled: true
  storageclass: ""

cache:
  name: "redis-cache"
  enabled: true
  memory: 100mb

env:
  var1:
    name: "A_VAR"
    value: "A_VALUE"
  var2:
    name: ""
    value: ""
