image: ""
imagePullSecrets: ""

db:
  enabled: true
  type: "postgres"
  host: ""
  name: ""
  username: "postgres"
  password: ""

web:
  name: "web"
  enabled: true
  host: ""
  entrypoint: ""
  command: ""

worker:
  name: "worker"
  enabled: true
  entrypoint: ""
  command: ""

redis:
  name: "redis"
  enabled: true
  storageclass: ""

cache:
  name: "cache"
  enabled: true
  memory: 100mb

env: {}
