image: "private.repo/image:tag"
imagePullSecrets: "test"

db:
  enabled: true
  type: "postgres"
  host: "db"
  name: "app"
  username: "postgres"
  password: "password"

web:
  name: "web"
  enabled: true
  host: "example.dev"
  host2: "example2.dev"
  forcessl: false
  entrypoint: ""
  command: ""
  balancer: "nginx-ingress"
  certificates: "cert-manager"

worker:
  name: "worker"
  enabled: true
  entrypoint: ""
  command: ""

scheduler:
  name: "scheduler"
  enabled: false
  entrypoint: ""
  command: ""

redis:
  name: "redis"
  enabled: true
  storageclass: ""

cache:
  name: "redis-cache"
  enabled: true
  memory: 100mb

env:
  var1:
    name: "A_VAR"
    value: "A_VALUE"
  var2:
    name: ""
    value: ""
