image: ""
imagePullSecrets: ""

db:
  enabled: true
  type: "postgres"
  host: ""
  name: ""
  username: "postgres"
  password: ""
  url: ""

web:
  name: "web"
  enabled: true
  host: ""
  host2: ""
  forcessl: true
  entrypoint: ""
  command: ""
  balancer: "nginx-ingress"
  certificates: "cert-manager"
  certificatesissuer: ""

worker:
  name: "worker"
  enabled: true
  entrypoint: ""
  command: ""

scheduler:
  name: "scheduler"
  enabled: false
  entrypoint: ""
  command: ""

redis:
  name: "redis"
  enabled: true
  storageclass: ""

cache:
  name: "cache"
  enabled: true
  memory: 100mb

env: {}
