{{- if .Values.cache.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.cache.name }}
  labels:
    app: {{ .Values.cache.name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: {{ .Values.cache.name }}
    spec:
      containers:
      - name: {{ .Values.cache.name }}
        image: redis:latest
        imagePullPolicy: Always
        args:
        - redis-server
        - --save
        - ""
        - --maxmemory
        - {{ .Values.cache.memory }}
        - --maxmemory-policy
        - allkeys-lru
        ports:
        - containerPort: 6379
          name: cache-port
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 6379
          timeoutSeconds: 2
{{- end }}
