{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: {{ .Values.redis.name }}
    release: {{ .Release.Name }}
{{- end }}
