{{- if .Values.redis.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- if .Values.redis.storageclass }}
{{- if (eq "-" .Values.redis.storageclass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.redis.storageclass }}"
{{- end }}
{{- end }}
{{- end }}
