{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.scheduler.name }}
  labels:
    app: {{ .Values.scheduler.name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: {{ .Values.scheduler.name }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
{{- end }}
      containers:
      - name: {{ .Values.scheduler.name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        command:
{{- range $part := (.Values.worker.entrypoint | split " ") }}
        - {{ $part | quote }}
{{- end }}
{{- if .Values.worker.command }}
        args:
{{- range $part := (.Values.worker.command | split " ") }}
        - {{ $part | quote }}
{{- end }}
{{- end }}
{{- include "app.vars" . | indent 8 }}
{{- end }}
