{{- if .Values.web.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.web.name }}
  labels:
    app: {{ .Values.web.name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if eq .Values.web.certificates "cert-manager" }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.web.forcessl }}"
    {{- if eq .Values.web.balancer "nginx-ingress" }}
    kubernetes.io/ingress.class: nginx
    {{- end }}
    kubernetes.io/tls-acme: "true"
{{- end }}
spec:
  tls:
  - hosts:
      - {{ .Values.web.host }}
    secretName: {{ .Values.web.name }}-tls-crt
{{- if .Values.web.host2 }}
  - hosts:
      - {{ .Values.web.host2 }}
    secretName: {{ .Values.web.name }}2-tls-crt
{{- end }}
  rules:
  - host: {{ .Values.web.host }}
    http:
      paths:
        - backend:
            serviceName: {{ .Values.web.name }}
            servicePort: 80
{{- if .Values.web.host2 }}
  - host: {{ .Values.web.host2 }}
    http:
      paths:
        - backend:
            serviceName: {{ .Values.web.name }}
            servicePort: 80
{{- end }}
{{- end }}
