{{- if .Values.worker.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.worker.name }}
  labels:
    app: {{ .Values.worker.name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: {{ .Values.worker.name }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
{{- end }}
      containers:
      - name: {{ .Values.worker.name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
{{- if or .Values.worker.entrypoint .Values.worker.command }}
{{- if .Values.worker.entrypoint }}
        command:
{{- range $part := (.Values.worker.entrypoint | split " ") }}
        - {{ $part | quote }}
{{- end }}
{{- end }}
{{- if .Values.worker.command }}
        args:
{{- range $part := (.Values.worker.command | split " ") }}
        - {{ $part | quote }}
{{- end }}
{{- end }}
{{- else }}
        command:
        - sh
        - "-vc"
        - |
          bundle exec rake db:migrate; \
          bundle exec sidekiq
        args:
        - ""
{{- end}}
{{- include "app.vars" . | indent 8 }}
{{- end }}
